name: pr

on:
  pull_request:

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: [iot-action-k8s]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Build
        run: npm run build